# Generated by Django 5.0.6 on 2024-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='date_earned',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issuer',
        ),
    ]
